import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  scroll: {
    flex: 1,
    backgroundColor: "#070b16",
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 48,
    gap: 20,
  },
  contentPhone: {
    paddingHorizontal: 12,
    paddingTop: 16,
    paddingBottom: 28,
    gap: 16,
  },
  contentTablet: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 1120,
    paddingHorizontal: 22,
  },
  contentLaptop: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 1560,
    paddingHorizontal: 28,
  },
  pageBackdrop: {
    ...StyleSheet.absoluteFill,
    width: "100%",
    height: "100%",
    opacity: 0.5,
  },
  pageBackdropOverlay: {
    ...StyleSheet.absoluteFill,
    opacity: 0.58,
  },
  pageGlow: {
    position: "absolute",
    top: -120,
    right: -80,
    width: 240,
    height: 240,
    borderRadius: 999,
    opacity: 0.1,
  },
  navbar: {
    gap: 16,
    zIndex: 100,
  },
  navbarTablet: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  navbarLaptop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  navbarMobile: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  navBrandBlock: {
    flexShrink: 1,
  },
  navBrandPressable: {
    alignSelf: "flex-start",
  },
  navBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  navLogo: {
    width: 42,
    height: 42,
  },
  navLogoPhone: {
    width: 34,
    height: 34,
  },
  navBrand: {
    color: "#f8fafc",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  navBrandPhone: {
    fontSize: 22,
  },
  navSubtle: {
    color: "#8ea0bf",
    marginTop: 4,
  },
  navSubtlePhone: {
    fontSize: 12,
  },
  navActions: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
  },
  navActionsMobile: {
    justifyContent: "flex-start",
  },
  navRightGroup: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    flexWrap: "wrap",
  },
  navRightGroupMobile: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  navActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "#11182d",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.12)",
  },
  navActionButtonLabel: {
    color: "#f8fafc",
    fontWeight: "800",
  },
  cardBackgroundToggle: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 64,
  },
  cardBackgroundToggleMobile: {
    width: "100%",
  },
  cardBackgroundToggleLabel: {
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  navMenuWrap: {
    position: "relative",
    minWidth: 230,
    maxWidth: 320,
    flexGrow: 1,
    alignSelf: "stretch",
    zIndex: 120,
  },
  navMenuWrapMobile: {
    minWidth: 0,
    maxWidth: undefined,
    width: "100%",
  },
  navCharacterButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minHeight: 46,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.18)",
  },
  navCharacterSeal: {
    width: 30,
    height: 30,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1b2440",
  },
  navCharacterSealText: {
    color: "#fbbf24",
    fontWeight: "800",
  },
  navCharacterText: {
    flex: 1,
  },
  navCharacterLabel: {
    color: "#91a1bd",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  navCharacterName: {
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 1,
  },
  navChevron: {
    color: "#f8fafc",
    fontSize: 14,
  },
  dropdown: {
    marginTop: 8,
    borderRadius: 18,
    backgroundColor: "#0b1224",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
    overflow: "hidden",
  },
  dropdownFloating: {
    position: "absolute",
    top: "100%",
    right: 0,
    left: 0,
    marginTop: 8,
    borderRadius: 18,
    backgroundColor: "#0b1224",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
    overflow: "hidden",
    zIndex: 140,
    ...Platform.select({
      web: {
        boxShadow: "0px 10px 16px rgba(0, 0, 0, 0.28)",
      } as object,
      default: {
        shadowColor: "#000",
        shadowOpacity: 0.28,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 10 },
        elevation: 12,
      },
    }),
  },
  dropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(148, 163, 184, 0.1)",
  },
  dropdownItemActive: {
    backgroundColor: "#141f3a",
  },
  dropdownTitle: {
    color: "#f8fafc",
    fontWeight: "700",
  },
  dropdownTitleActive: {
    color: "#fbbf24",
  },
  dropdownSubtitle: {
    color: "#8ea0bf",
    marginTop: 3,
    lineHeight: 18,
    fontSize: 12,
  },
  hero: {
    position: "relative",
    gap: 0,
    padding: 0,
    borderRadius: 12,
    backgroundColor: "#0b1020",
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.14)",
    overflow: "hidden",
    zIndex: 20,
    ...Platform.select({
      web: {
        boxShadow: "0px 18px 42px rgba(0, 0, 0, 0.34)",
      } as object,
      default: {
        shadowColor: "#000",
        shadowOpacity: 0.32,
        shadowRadius: 24,
        shadowOffset: { width: 0, height: 16 },
        elevation: 10,
      },
    }),
  },
  heroTablet: {
    flexDirection: "row",
    alignItems: "stretch",
    flexWrap: "wrap",
  },
  heroMobile: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  heroVisualCard: {
    flexBasis: 230,
    flexGrow: 0,
    minWidth: 220,
    maxWidth: 280,
    flexShrink: 1,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    padding: 18,
    borderRightWidth: 1,
    borderRightColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(0, 0, 0, 0.18)",
  },
  heroVisualCardPhone: {
    width: "100%",
    flexBasis: "auto",
    maxHeight: undefined,
    minWidth: 0,
    maxWidth: 260,
    alignSelf: "center",
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRightWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  heroVisualBadge: {
    alignSelf: "stretch",
    alignItems: "center",
  },
  heroVisualBadgeLabel: {
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.9,
  },
  toast: {
    position: "absolute",
    top: 14,
    left: 16,
    right: 16,
    alignSelf: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    zIndex: 200,
  },
  toastText: {
    fontWeight: "800",
    textAlign: "center",
  },
  overlayBackdrop: {
    flex: 1,
    backgroundColor: "rgba(3, 6, 14, 0.58)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  overlayCard: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "88%",
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 16,
  },
  imageLibraryModal: {
    maxWidth: 1040,
  },
  overlayScroll: {
    flexGrow: 0,
  },
  overlayScrollContent: {
    gap: 16,
    paddingBottom: 4,
  },
  overlayHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "flex-start",
  },
  overlayHeaderText: {
    flex: 1,
    gap: 4,
  },
  overlayTitle: {
    fontSize: 22,
    fontWeight: "900",
  },
  overlaySubtitle: {
    lineHeight: 20,
  },
  overlayCloseButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: "rgba(15, 23, 42, 0.18)",
  },
  overlayCloseButtonLabel: {
    fontWeight: "800",
  },
  overlayOptionList: {
    gap: 12,
  },
  imageLibraryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  imageLibrarySearchWrap: {
    gap: 8,
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
  },
  imageLibrarySearchInput: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#0d1426",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
  },
  imageLibrarySearchHint: {
    fontSize: 12,
    lineHeight: 18,
  },
  imageLibraryCard: {
    width: 148,
    gap: 10,
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
  },
  imageLibraryCardLabel: {
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  imageLibraryCardTags: {
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
  },
  overlayOptionCard: {
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
  },
  overlayOptionTitle: {
    fontSize: 16,
    fontWeight: "800",
  },
  overlayOptionDescription: {
    lineHeight: 20,
  },
  bioDialogCard: {
    maxHeight: 420,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
  },
  bioDialogScroll: {
    maxHeight: 380,
  },
  bioDialogText: {
    fontSize: 14,
    lineHeight: 22,
  },
  damageEditorCard: {
    gap: 12,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
  },
  damageToggle: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  damageToggleLabel: {
    fontWeight: "800",
  },
  creationSummaryCard: {
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
  },
  creationSummaryTitle: {
    fontSize: 18,
    fontWeight: "900",
  },
  creationSummaryDescription: {
    lineHeight: 20,
  },
  creationSummaryMeta: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  overlayActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    flexWrap: "wrap",
  },
  overlaySecondaryButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  overlaySecondaryButtonLabel: {
    fontWeight: "800",
  },
  overlayPrimaryButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  overlayPrimaryButtonLabel: {
    fontWeight: "900",
  },
  editorModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(3, 6, 14, 0.72)",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  editorModalWrap: {
    width: "100%",
    maxWidth: 920,
    alignSelf: "center",
    maxHeight: "92%",
  },
  editorModalScroll: {
    flexGrow: 0,
  },
  editorModalContent: {
    paddingVertical: 4,
  },
  sectionEditButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionEditButtonLabel: {
    fontSize: 16,
    fontWeight: "800",
  },
  heroText: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 460,
    minWidth: 0,
    gap: 18,
    alignSelf: "stretch",
    justifyContent: "center",
    padding: 24,
  },
  heroAccentBar: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: 5,
    zIndex: 3,
  },
  heroKickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  heroKicker: {
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  heroSignal: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  heroTopRowPhone: {
    flexDirection: "column",
  },
  heroIdentity: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  eyebrow: {
    color: "#fbbf24",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  title: {
    color: "#f8fafc",
    fontSize: 42,
    fontWeight: "900",
  },
  titlePhone: {
    fontSize: 31,
  },
  description: {
    color: "#b9c6da",
    fontSize: 15,
  },
  heroDescription: {
    lineHeight: 22,
  },
  heroChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heroChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
  },
  heroChipLabel: {
    fontSize: 12,
    fontWeight: "800",
  },
  heroBioButton: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 2,
  },
  heroBioButtonLabel: {
    fontWeight: "800",
  },
  heroBioPreview: {
    maxWidth: 760,
    lineHeight: 22,
    fontSize: 14,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: "rgba(255, 255, 255, 0.16)",
  },
  heroActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  heroEditButton: {
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
  heroEditButtonLabel: {
    fontWeight: "900",
  },
  heroEditIconButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  heroEditIconButtonFloating: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 30,
  },
  heroEditIconLabel: {
    fontSize: 16,
    fontWeight: "800",
  },
  editorActions: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  editorBioButton: {
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
  },
  editorBioButtonLabel: {
    fontWeight: "800",
  },
  editorBioButtonHint: {
    fontSize: 12,
    lineHeight: 18,
  },
  editorDangerButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#3a1420",
  },
  editorDangerButtonLabel: {
    color: "#fecdd3",
    fontWeight: "800",
  },
  editorGhostButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#11182d",
  },
  editorGhostButtonLabel: {
    color: "#c8d5e8",
    fontWeight: "700",
  },
  editorPrimaryButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#fbbf24",
  },
  editorPrimaryButtonLabel: {
    color: "#3f2200",
    fontWeight: "900",
  },
  editorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  editorField: {
    flexGrow: 1,
    flexBasis: 180,
    gap: 6,
  },
  editorFieldOverlayTop: {
    zIndex: 90,
  },
  editorFieldOverlayMid: {
    zIndex: 80,
  },
  themePicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  themeOption: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  themeOptionLabel: {
    fontWeight: "700",
    fontSize: 12,
  },
  themeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  themeCard: {
    width: 196,
    minHeight: 146,
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
  },
  themeCardPreview: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  themeCardSwatchPrimary: {
    width: 56,
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
  },
  themeCardSwatchSecondary: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderWidth: 1,
  },
  themeCardSwatchAccent: {
    width: 16,
    height: 56,
    borderRadius: 999,
  },
  themeCardBody: {
    gap: 4,
  },
  themeCardTitle: {
    fontSize: 15,
    fontWeight: "800",
  },
  themeCardDescription: {
    fontSize: 12,
    lineHeight: 18,
  },
  themeCardActivePill: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  themeCardActivePillLabel: {
    fontSize: 11,
    fontWeight: "900",
  },
  editorFieldLabel: {
    color: "#9caec8",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  editorHint: {
    color: "#8ea0bf",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
  },
  editorDropdownWrap: {
    position: "relative",
    zIndex: 60,
  },
  editorThemeControlRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
    flexWrap: "wrap",
  },
  editorThemeDropdownWrap: {
    flex: 1,
    minWidth: 180,
  },
  editorCardBackgroundToggle: {
    minHeight: 44,
    minWidth: 150,
    paddingVertical: 10,
    borderRadius: 12,
  },
  editorSelectButton: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  editorSelectValue: {
    flex: 1,
    fontWeight: "700",
  },
  editorSelectChevron: {
    fontSize: 14,
    fontWeight: "800",
  },
  editorDropdownMenu: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    marginTop: 8,
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
    zIndex: 80,
    ...Platform.select({
      web: {
        boxShadow: "0px 8px 14px rgba(0, 0, 0, 0.24)",
      } as object,
      default: {
        shadowColor: "#000",
        shadowOpacity: 0.24,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 8 },
        elevation: 10,
      },
    }),
  },
  editorInput: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#0d1426",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    color: "#f8fafc",
  },
  bioEditorInput: {
    minHeight: 280,
  },
  editorTextArea: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  editorGroup: {
    gap: 12,
  },
  editorGroupHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  editorGroupTitle: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "800",
  },
  editorAddButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#1b2740",
  },
  editorAddButtonLabel: {
    color: "#f8fafc",
    fontWeight: "800",
    fontSize: 12,
  },
  editorResourceBlock: {
    gap: 10,
    paddingTop: 6,
  },
  editorResourceTitle: {
    color: "#fbbf24",
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  editorList: {
    gap: 12,
  },
  editorCard: {
    gap: 12,
    padding: 12,
    borderRadius: 18,
    backgroundColor: "#0d1426",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.12)",
  },
  editorCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  editorCardTitle: {
    color: "#f8fafc",
    fontWeight: "800",
  },
  editorRemoveButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#3a1420",
  },
  editorRemoveButtonLabel: {
    color: "#fecdd3",
    fontWeight: "800",
    fontSize: 12,
  },
  editorInlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  editorInlineLabel: {
    flex: 1,
    color: "#f8fafc",
    fontWeight: "700",
  },
  editorInlineInputWrap: {
    width: 110,
  },
  editorInventoryBlock: {
    gap: 8,
  },
  editorToggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  editorToggleGroup: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
  },
  editorMediaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  editorDeletePanel: {
    gap: 10,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
  },
  editorDeleteTitle: {
    fontSize: 15,
    fontWeight: "800",
  },
  editorDeleteHint: {
    fontSize: 12,
    lineHeight: 18,
  },
  editorDeleteActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  editorUploadButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#1b2740",
  },
  editorUploadButtonLabel: {
    color: "#f8fafc",
    fontWeight: "800",
  },
  editorToggleButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: "#11182d",
  },
  editorToggleButtonActive: {
    backgroundColor: "#1b2740",
  },
  editorToggleButtonLabel: {
    color: "#f8fafc",
    fontWeight: "800",
  },
  bannerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tabletSectionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 18,
  },
  tabletPrimaryColumn: {
    flexGrow: 1.05,
    flexShrink: 1,
    flexBasis: 520,
    minWidth: 300,
    gap: 18,
  },
  tabletPrimaryColumnTablet: {
    flexGrow: 1,
  },
  tabletPrimaryColumnLaptop: {
    flexGrow: 1.08,
  },
  tabletSecondaryColumn: {
    flexGrow: 0.95,
    flexShrink: 1,
    flexBasis: 420,
    minWidth: 300,
    gap: 18,
  },
  tabletSecondaryColumnTablet: {
    flexGrow: 1,
  },
  tabletSecondaryColumnLaptop: {
    flexGrow: 0.92,
  },
  bannerTag: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "#11182d",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.12)",
  },
  bannerTagLabel: {
    color: "#dbe4f0",
    fontWeight: "700",
    fontSize: 12,
  },
  sheetZoneHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 12,
    flexWrap: "wrap",
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 4,
    borderRadius: 10,
    backgroundColor: "rgba(0, 0, 0, 0.18)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  sheetZoneTitle: {
    fontSize: 20,
    fontWeight: "900",
  },
  sheetZoneSubtitle: {
    flexShrink: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  tacticalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 18,
  },
  tacticalColumn: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 380,
    minWidth: 320,
    gap: 18,
  },
  tacticalColumnWide: {
    flexGrow: 1.25,
    flexShrink: 1,
    flexBasis: 520,
    minWidth: 320,
    gap: 18,
  },
  arsenalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 18,
  },
  arsenalColumn: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 360,
    minWidth: 300,
    gap: 18,
  },
  arsenalColumnWide: {
    flexGrow: 1.2,
    flexShrink: 1,
    flexBasis: 460,
    minWidth: 320,
    gap: 18,
  },
  quickActionsCard: {
    gap: 14,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  quickActionsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  quickActionsHeaderText: {
    flex: 1,
    gap: 4,
  },
  quickActionsHint: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "700",
  },
  quickActionsTitle: {
    fontSize: 18,
    fontWeight: "900",
  },
  quickActionsMeta: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  quickActionsButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  quickActionButton: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 16,
    borderWidth: 1,
  },
  quickActionButtonSingle: {
    width: "100%",
  },
  quickActionButtonDouble: {
    flexBasis: "48%",
    flexGrow: 1,
  },
  quickActionButtonTriple: {
    flexBasis: "31%",
    flexGrow: 1,
  },
  quickActionIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  quickActionIcon: {
    fontSize: 16,
    fontWeight: "900",
  },
  quickActionBody: {
    flex: 1,
    gap: 4,
  },
  quickActionButtonLabel: {
    fontSize: 14,
    fontWeight: "900",
  },
  quickActionDescription: {
    fontSize: 12,
    lineHeight: 18,
  },
  quickActionValue: {
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  quickModeRow: {
    flexDirection: "row",
    gap: 10,
  },
  quickModeButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  quickModeButtonLabel: {
    fontWeight: "800",
  },
  quickCastHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  quickCastRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  quickCastBody: {
    flex: 1,
    gap: 6,
  },
  quickCastScalingHint: {
    fontSize: 12,
    lineHeight: 18,
  },
  quickCastCost: {
    color: "#082f49",
    backgroundColor: "#bae6fd",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: "hidden",
    fontWeight: "900",
  },
  quickCastCostReduced: {
    color: "#3f2200",
    backgroundColor: "#fbbf24",
  },
  quickCastDetailCard: {
    gap: 12,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 2,
  },
  quickCastDetailTitle: {
    fontSize: 16,
    fontWeight: "900",
  },
  quickCastDetailText: {
    lineHeight: 20,
  },
  quickCastAdjustRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  quickCastAdjustButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
  },
  quickCastAdjustButtonLabel: {
    fontWeight: "900",
  },
  quickCastAdjustValue: {
    minWidth: 96,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
  },
  quickCastAdjustValueLabel: {
    fontWeight: "900",
  },
  dualColumns: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 18,
    alignItems: "stretch",
  },
  dualColumn: {
    flexGrow: 1,
    flexBasis: 320,
    alignSelf: "stretch",
  },
  equalHeightCard: {
    flex: 1,
  },
  effectList: {
    gap: 12,
  },
  effectCard: {
    gap: 10,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
  },
  effectHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
  },
  effectHeaderText: {
    flex: 1,
    gap: 4,
  },
  effectTitle: {
    fontSize: 16,
    fontWeight: "800",
  },
  effectSource: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  effectActiveToggle: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  effectActiveToggleLabel: {
    fontWeight: "800",
    fontSize: 12,
  },
  effectDescription: {
    lineHeight: 20,
  },
  effectFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  effectTurns: {
    fontWeight: "800",
  },
  resistanceList: {
    gap: 12,
  },
  resistanceCard: {
    gap: 8,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
  },
  resistanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  resistanceLabel: {
    fontWeight: "800",
    fontSize: 15,
    flex: 1,
  },
  resistanceBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  resistanceBadgeLabel: {
    fontWeight: "800",
    fontSize: 12,
  },
  resourceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  resourceCard: {
    flexGrow: 1,
    flexBasis: 210,
    alignItems: "center",
    gap: 10,
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderRadius: 22,
    backgroundColor: "#0d1426",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
  },
  resourceName: {
    color: "#f8fafc",
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  resourceGlyphFrame: {
    width: 96,
    height: 96,
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  resourceGlyphWrap: {
    width: 84,
    height: 84,
    alignItems: "center",
    justifyContent: "center",
  },
  resourceGlyphFillMask: {
    width: 96,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  resourceGlyphFill: {
    fontSize: 76,
    lineHeight: 82,
  },
  resourceCount: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "900",
  },
  resourceBonus: {
    color: "#fbbf24",
    fontSize: 13,
    fontWeight: "700",
  },
  resourceButtons: {
    flexDirection: "row",
    gap: 10,
  },
  attackGlyph: {
    color: "#fbbf24",
    fontSize: 76,
    lineHeight: 82,
  },
  adjustButton: {
    minWidth: 54,
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#1b2740",
  },
  adjustButtonLabel: {
    color: "#f8fafc",
    fontWeight: "800",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: 140,
    gap: 6,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#0d1426",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.12)",
  },
  statHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#17223c",
  },
  statIcon: {
    color: "#fbbf24",
    fontSize: 15,
    fontWeight: "800",
  },
  statLabel: {
    color: "#9caec8",
    textTransform: "capitalize",
  },
  statValue: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
    width: "100%",
  },
  table: {
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.12)",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#121c34",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  tableHeaderText: {
    color: "#8ea0bf",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#0d1426",
    borderTopWidth: 1,
    borderTopColor: "rgba(148, 163, 184, 0.08)",
  },
  tableNameColumn: {
    flex: 1,
  },
  tableCell: {
    color: "#f8fafc",
  },
  tableBonus: {
    color: "#fbbf24",
    fontWeight: "900",
  },
  inventoryList: {
    gap: 10,
  },
  inventoryItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 18,
    backgroundColor: "#0d1426",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.1)",
  },
  inventoryBody: {
    flex: 1,
    gap: 3,
  },
  inventoryName: {
    color: "#f8fafc",
    fontWeight: "700",
  },
  inventoryNotes: {
    color: "#8ea0bf",
    fontSize: 12,
  },
  inventoryQty: {
    color: "#fbbf24",
    fontWeight: "900",
  },
  assetTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  assetTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  assetTagLabel: {
    fontSize: 12,
    fontWeight: "700",
  },
  assetGrid: {
    gap: 14,
  },
  assetCard: {
    flexDirection: "row",
    gap: 14,
    padding: 14,
    borderRadius: 22,
    backgroundColor: "#0d1426",
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.12)",
  },
  assetCardActive: {
    backgroundColor: "#122237",
    borderColor: "rgba(251, 191, 36, 0.4)",
  },
  equipmentList: {
    gap: 14,
  },
  equipmentCard: {
    flexDirection: "row",
    gap: 16,
    padding: 16,
    borderRadius: 24,
    backgroundColor: "#0d1426",
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.12)",
  },
  assetVisual: {
    width: 84,
    height: 84,
    borderRadius: 20,
  },
  characterVisual: {
    width: 96,
    height: 96,
    borderRadius: 24,
  },
  assetVisualButton: {
    borderRadius: 20,
  },
  assetVisualSmall: {
    width: 42,
    height: 42,
    borderRadius: 12,
  },
  assetFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#17223c",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.12)",
  },
  assetFallbackActive: {
    backgroundColor: "#2a3557",
    borderColor: "rgba(251, 191, 36, 0.35)",
  },
  assetFallbackText: {
    fontSize: 34,
  },
  assetFallbackSmallText: {
    fontSize: 18,
  },
  assetBody: {
    flex: 1,
    gap: 8,
  },
  equipmentBody: {
    flex: 1,
    gap: 8,
  },
  assetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
  },
  assetBadgeColumn: {
    alignItems: "flex-end",
    gap: 8,
  },
  assetHeading: {
    flex: 1,
    gap: 3,
  },
  assetTitle: {
    color: "#f8fafc",
    fontSize: 17,
    fontWeight: "800",
  },
  assetMeta: {
    color: "#8ea0bf",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  costBadge: {
    color: "#082f49",
    backgroundColor: "#bae6fd",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: "hidden",
    fontWeight: "900",
  },
  costBadgeReduced: {
    color: "#3f2200",
    backgroundColor: "#fbbf24",
  },
  activeBadge: {
    color: "#3f2200",
    backgroundColor: "#fde68a",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: "hidden",
    fontWeight: "900",
  },
  assetDescription: {
    color: "#d7deeb",
    lineHeight: 21,
  },
  assetEffect: {
    color: "#b1c0d7",
    lineHeight: 20,
  },
  emptyText: {
    color: "#7d8eab",
  },
});
