// This file is auto-generated by scripts/generate-image-library.js.
// Do not edit it by hand.

export type ImageLibraryCategory =
  | "character"
  | "spell"
  | "equipment"
  | "inventory";

export type LocalImageOption = {
  id: string;
  label: string;
  category: ImageLibraryCategory;
  tags: string[];
  imageModule: number;
};

export const LOCAL_IMAGE_LIBRARY: Record<ImageLibraryCategory, LocalImageOption[]> = {
  character: [
    {
      id: "char-cleric-hunter",
      label: "Cleric Hunter",
      category: "character",
      tags: ["character","cleric","hunter"],
      imageModule: require("../../assets/characters/cleric_hunter.png"),
    },
    {
      id: "char-demoniste",
      label: "Demoniste",
      category: "character",
      tags: ["character","demoniste"],
      imageModule: require("../../assets/characters/demoniste.png"),
    },
    {
      id: "char-guerisseur-foret",
      label: "Guerisseur Foret",
      category: "character",
      tags: ["character","foret","guerisseur"],
      imageModule: require("../../assets/characters/guerisseur_foret.png"),
    },
    {
      id: "char-paladin-ange",
      label: "Paladin Ange",
      category: "character",
      tags: ["ange","character","paladin"],
      imageModule: require("../../assets/characters/paladin_ange.png"),
    }
  ],
  spell: [
    {
      id: "spell-demon-summon",
      label: "Demon Summon",
      category: "spell",
      tags: ["demon","spell","summon"],
      imageModule: require("../../assets/spells/demon_summon.png"),
    },
    {
      id: "spell-holy-cross",
      label: "Holy Cross",
      category: "spell",
      tags: ["cross","holy","spell"],
      imageModule: require("../../assets/spells/holy_cross.png"),
    },
    {
      id: "spell-holy-hammer",
      label: "Holy Hammer",
      category: "spell",
      tags: ["hammer","holy","spell"],
      imageModule: require("../../assets/spells/holy_hammer.png"),
    },
    {
      id: "spell-holy-shield",
      label: "Holy Shield",
      category: "spell",
      tags: ["holy","shield","spell"],
      imageModule: require("../../assets/spells/holy_shield.png"),
    }
  ],
  equipment: [
    {
      id: "equip-amulette",
      label: "Amulette",
      category: "equipment",
      tags: ["amulette","equipment"],
      imageModule: require("../../assets/equipment/amulette.png"),
    },
    {
      id: "equip-armure-chevalier-rouge",
      label: "Armure Chevalier Rouge",
      category: "equipment",
      tags: ["armure","chevalier","equipment","rouge"],
      imageModule: require("../../assets/equipment/armure_chevalier_rouge.png"),
    },
    {
      id: "equip-armure-chevalier",
      label: "Armure Chevalier",
      category: "equipment",
      tags: ["armure","chevalier","equipment"],
      imageModule: require("../../assets/equipment/armure_chevalier.png"),
    },
    {
      id: "equip-armure-demo-femme",
      label: "Armure Demo Femme",
      category: "equipment",
      tags: ["armure","demo","equipment","femme"],
      imageModule: require("../../assets/equipment/armure_demo_femme.png"),
    },
    {
      id: "equip-armure-demoniste",
      label: "Armure Demoniste",
      category: "equipment",
      tags: ["armure","demoniste","equipment"],
      imageModule: require("../../assets/equipment/armure_demoniste.png"),
    },
    {
      id: "equip-armure-divine",
      label: "Armure Divine",
      category: "equipment",
      tags: ["armure","divine","equipment"],
      imageModule: require("../../assets/equipment/armure_divine.png"),
    },
    {
      id: "equip-armure-druide",
      label: "Armure Druide",
      category: "equipment",
      tags: ["armure","druide","equipment"],
      imageModule: require("../../assets/equipment/armure_druide.png"),
    },
    {
      id: "equip-armure-pal",
      label: "Armure Pal",
      category: "equipment",
      tags: ["armure","equipment","pal"],
      imageModule: require("../../assets/equipment/armure_pal.png"),
    },
    {
      id: "equip-armure-roublard",
      label: "Armure Roublard",
      category: "equipment",
      tags: ["armure","equipment","roublard"],
      imageModule: require("../../assets/equipment/armure_roublard.png"),
    },
    {
      id: "equip-baton-demo-2",
      label: "Baton Demo 2",
      category: "equipment",
      tags: ["2","baton","demo","equipment"],
      imageModule: require("../../assets/equipment/baton_demo_2.png"),
    },
    {
      id: "equip-baton-demo",
      label: "Baton Demo",
      category: "equipment",
      tags: ["baton","demo","equipment"],
      imageModule: require("../../assets/equipment/baton_demo.png"),
    },
    {
      id: "equip-baton-priest",
      label: "Baton Priest",
      category: "equipment",
      tags: ["baton","equipment","priest"],
      imageModule: require("../../assets/equipment/baton_priest.png"),
    },
    {
      id: "equip-bouclier-death",
      label: "Bouclier Death",
      category: "equipment",
      tags: ["bouclier","death","equipment"],
      imageModule: require("../../assets/equipment/bouclier_death.png"),
    },
    {
      id: "equip-bow",
      label: "Bow",
      category: "equipment",
      tags: ["bow","equipment"],
      imageModule: require("../../assets/equipment/bow.png"),
    },
    {
      id: "equip-casque-demoniste",
      label: "Casque Demoniste",
      category: "equipment",
      tags: ["casque","demoniste","equipment"],
      imageModule: require("../../assets/equipment/casque_demoniste.png"),
    },
    {
      id: "equip-crossbow",
      label: "Crossbow",
      category: "equipment",
      tags: ["crossbow","equipment"],
      imageModule: require("../../assets/equipment/crossbow.png"),
    },
    {
      id: "equip-dagger",
      label: "Dagger",
      category: "equipment",
      tags: ["dagger","equipment"],
      imageModule: require("../../assets/equipment/dagger.png"),
    },
    {
      id: "equip-grimoire-demo",
      label: "Grimoire Demo",
      category: "equipment",
      tags: ["demo","equipment","grimoire"],
      imageModule: require("../../assets/equipment/grimoire_demo.png"),
    },
    {
      id: "equip-grimoire-priest",
      label: "Grimoire Priest",
      category: "equipment",
      tags: ["equipment","grimoire","priest"],
      imageModule: require("../../assets/equipment/grimoire_priest.png"),
    },
    {
      id: "equip-grimoire",
      label: "Grimoire",
      category: "equipment",
      tags: ["equipment","grimoire"],
      imageModule: require("../../assets/equipment/grimoire.png"),
    },
    {
      id: "equip-gun",
      label: "Gun",
      category: "equipment",
      tags: ["equipment","gun"],
      imageModule: require("../../assets/equipment/gun.png"),
    },
    {
      id: "equip-kevlar-chelou",
      label: "Kevlar Chelou",
      category: "equipment",
      tags: ["chelou","equipment","kevlar"],
      imageModule: require("../../assets/equipment/kevlar_chelou.png"),
    },
    {
      id: "equip-kevlar-drood",
      label: "Kevlar Drood",
      category: "equipment",
      tags: ["drood","equipment","kevlar"],
      imageModule: require("../../assets/equipment/kevlar_drood.png"),
    },
    {
      id: "equip-kevlar-enchanteur-femme",
      label: "Kevlar Enchanteur Femme",
      category: "equipment",
      tags: ["enchanteur","equipment","femme","kevlar"],
      imageModule: require("../../assets/equipment/kevlar_enchanteur_femme.png"),
    },
    {
      id: "equip-kevlar-enchanteur",
      label: "Kevlar Enchanteur",
      category: "equipment",
      tags: ["enchanteur","equipment","kevlar"],
      imageModule: require("../../assets/equipment/kevlar_enchanteur.png"),
    },
    {
      id: "equip-kevlar-paladin-femme",
      label: "Kevlar Paladin Femme",
      category: "equipment",
      tags: ["equipment","femme","kevlar","paladin"],
      imageModule: require("../../assets/equipment/kevlar_paladin_femme.png"),
    },
    {
      id: "equip-kevlar-rogue-femme",
      label: "Kevlar Rogue Femme",
      category: "equipment",
      tags: ["equipment","femme","kevlar","rogue"],
      imageModule: require("../../assets/equipment/kevlar_rogue_femme.png"),
    },
    {
      id: "equip-kevlar-rogue",
      label: "Kevlar Rogue",
      category: "equipment",
      tags: ["equipment","kevlar","rogue"],
      imageModule: require("../../assets/equipment/kevlar_rogue.png"),
    },
    {
      id: "equip-kevlar-sacre",
      label: "Kevlar Sacre",
      category: "equipment",
      tags: ["equipment","kevlar","sacre"],
      imageModule: require("../../assets/equipment/kevlar_sacre.png"),
    },
    {
      id: "equip-kevlar-simple-2",
      label: "Kevlar Simple 2",
      category: "equipment",
      tags: ["2","equipment","kevlar","simple"],
      imageModule: require("../../assets/equipment/kevlar_simple_2.png"),
    },
    {
      id: "equip-kevlar-simple",
      label: "Kevlar Simple",
      category: "equipment",
      tags: ["equipment","kevlar","simple"],
      imageModule: require("../../assets/equipment/kevlar_simple.png"),
    },
    {
      id: "equip-lantern-occulte",
      label: "Lantern Occulte",
      category: "equipment",
      tags: ["equipment","lantern","occulte"],
      imageModule: require("../../assets/equipment/lantern_occulte.png"),
    },
    {
      id: "equip-lantern-violette",
      label: "Lantern Violette",
      category: "equipment",
      tags: ["equipment","lantern","violette"],
      imageModule: require("../../assets/equipment/lantern_violette.png"),
    },
    {
      id: "equip-longsword",
      label: "Longsword",
      category: "equipment",
      tags: ["equipment","longsword"],
      imageModule: require("../../assets/equipment/longsword.png"),
    },
    {
      id: "equip-rapiere",
      label: "Rapiere",
      category: "equipment",
      tags: ["equipment","rapiere"],
      imageModule: require("../../assets/equipment/rapiere.png"),
    },
    {
      id: "equip-sword-2",
      label: "Sword 2",
      category: "equipment",
      tags: ["2","equipment","sword"],
      imageModule: require("../../assets/equipment/sword_2.png"),
    },
    {
      id: "equip-sword",
      label: "Sword",
      category: "equipment",
      tags: ["equipment","sword"],
      imageModule: require("../../assets/equipment/sword.png"),
    }
  ],
  inventory: [
    {
      id: "item-fiole-bleu",
      label: "Fiole Bleu",
      category: "inventory",
      tags: ["bleu","fiole","inventory"],
      imageModule: require("../../assets/inventory/fiole_bleu.png"),
    },
    {
      id: "item-fiole-rouge",
      label: "Fiole Rouge",
      category: "inventory",
      tags: ["fiole","inventory","rouge"],
      imageModule: require("../../assets/inventory/fiole_rouge.png"),
    },
    {
      id: "item-fiole-verte",
      label: "Fiole Verte",
      category: "inventory",
      tags: ["fiole","inventory","verte"],
      imageModule: require("../../assets/inventory/fiole_verte.png"),
    },
    {
      id: "item-livre-brule",
      label: "Livre Brule",
      category: "inventory",
      tags: ["brule","inventory","livre"],
      imageModule: require("../../assets/inventory/livre_brule.png"),
    },
    {
      id: "item-livre-demoniaque",
      label: "Livre Demoniaque",
      category: "inventory",
      tags: ["demoniaque","inventory","livre"],
      imageModule: require("../../assets/inventory/livre_demoniaque.png"),
    },
    {
      id: "item-livre-saint",
      label: "Livre Saint",
      category: "inventory",
      tags: ["inventory","livre","saint"],
      imageModule: require("../../assets/inventory/livre_saint.png"),
    },
    {
      id: "item-livre-sceller",
      label: "Livre Sceller",
      category: "inventory",
      tags: ["inventory","livre","sceller"],
      imageModule: require("../../assets/inventory/livre_sceller.png"),
    },
    {
      id: "item-livre",
      label: "Livre",
      category: "inventory",
      tags: ["inventory","livre"],
      imageModule: require("../../assets/inventory/livre.png"),
    },
    {
      id: "item-potion-rouge",
      label: "Potion Rouge",
      category: "inventory",
      tags: ["inventory","potion","rouge"],
      imageModule: require("../../assets/inventory/potion_rouge.png"),
    }
  ],
};
